name: Docker Image CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build -t dashmeet/docker-react -f Dockerfile.dev .
          
    - name: Test Docker image
      run: docker run dashmeet/docker-react npm test -- --coverage
      
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v18 
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: beanstalk-docker
        environment_name: Beanstalkdocker-env
        existing_bucket_name: elasticbeanstalk-us-west-1-251672825063
        region: us-west-1
        deployment_package: deploy.zip


